CREATE TABLE universities (
  id INT PRIMARY KEY,
  logo VARCHAR(255),
  address TEXT,
  name VARCHAR(255),
  type VARCHAR(50),
  location VARCHAR(255),
  website VARCHAR(255),
  status ENUM('aktif', 'pasif')
) CHARACTER SET utf8mb4;
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1001, 'https://yokatlas.yok.gov.tr/assets/img/logo/173499.png', 'Barbaros Mahallesi Sümer Kampüsü Kocasinan-KAYSERİ', 'ABDULLAH GÜL ÜNİVERSİTESİ', 'Devlet', 'Kayseri', 'http://www.agu.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1002, 'https://yokatlas.yok.gov.tr/assets/img/logo/326654.png', 'İçerenköy Mah. Kayışdağı Cad. No:32 İçerenköy 34752 Ataşehir İstanbul', 'ACIBADEM MEHMET ALİ AYDINLAR ÜNİVERSİTESİ', 'Vakıf', 'İstanbul', 'http://www.acibadem.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1003, 'https://yokatlas.yok.gov.tr/assets/img/logo/385368.png', 'Balcalı Mahallesi, Çatalan Caddesi No:201/1 01250 Sarıçam/ADANA', 'ADANA ALPARSLAN TÜRKEŞ BİLİM VE TEKNOLOJİ ÜNİVERSİTESİ', 'Devlet', 'Adana', 'http://www.atu.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1004, 'https://yokatlas.yok.gov.tr/assets/img/logo/100259.png', 'Adıyaman Üniversitesi, Altınşehir Mh. 3005 Sokak No:13 02040   ADIYAMAN', 'ADIYAMAN ÜNİVERSİTESİ', 'Devlet', 'Adıyaman', 'http://www.adiyaman.edu.tr/', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1005, 'https://yokatlas.yok.gov.tr/assets/img/logo/100869.png', 'Afyon Kocatepe Üniversitesi Rektörlüğü
ANS Kampusü Gazlıgöl Yolu Üzeri
AFYONKARAHİSAR', 'AFYON KOCATEPE ÜNİVERSİTESİ', 'Devlet', 'Afyonkarahisar', 'http://www.aku.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1006, 'https://yokatlas.yok.gov.tr/assets/img/logo/339999.png', 'Zafer Sağlık Külliyesi
Dörtyol Mah. 2078.Sok No:3
AFYONKARAHİSAR', 'AFYONKARAHİSAR SAĞLIK BİLİMLERİ ÜNİVERSİTESİ', 'Devlet', 'Afyonkarahisar', 'www.afsu.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1007, 'https://yokatlas.yok.gov.tr/assets/img/logo/101313.png', 'Erzurum yolu  4 km 04100 Merkez / AĞRI', 'AĞRI İBRAHİM ÇEÇEN ÜNİVERSİTESİ', 'Devlet', 'Ağrı', 'http://www.agri.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1008, 'https://yokatlas.yok.gov.tr/assets/img/logo/101458.png', 'Akdeniz Üniversitesi Kampüs Antalya', 'AKDENİZ ÜNİVERSİTESİ', 'Devlet', 'Antalya', 'http://www.akdeniz.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1009, 'https://yokatlas.yok.gov.tr/assets/img/logo/102005.png', 'Bahçesaray Mah.68100 AKSARAY', 'AKSARAY ÜNİVERSİTESİ', 'Devlet', 'Aksaray', 'www.aksaray.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1010, 'https://yokatlas.yok.gov.tr/assets/img/logo/274883.png', 'Kestel Mahallesi Üniversite Caddesi No:80 Alanya/ANTALYA', 'ALANYA ALAADDİN KEYKUBAT ÜNİVERSİTESİ', 'Devlet', 'Antalya', 'http://www.alanya.edu.tr/', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1011, 'https://yokatlas.yok.gov.tr/assets/img/logo/447835.png', 'Cikcilli Beldesi, Saraybeleni Mahallesi, Saraybeleni Cad. No:7, PK 80 07400, Alanya, ANTALYA', 'ALANYA ÜNİVERSİTESİ', 'Vakıf', 'Antalya', 'http://www.alanyauniversity.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1012, 'https://yokatlas.yok.gov.tr/assets/img/logo/326019.png', 'Mahmutbey, Dİlmenler Cd. No. 26 Bağcılar, İstanbul', 'ALTINBAŞ ÜNİVERSİTESİ', 'Vakıf', 'İstanbul', 'http://www.altinbas.edu.tr/tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1013, 'https://yokatlas.yok.gov.tr/assets/img/logo/102198.png', 'Akbilek Mah. Hakimiyet cad. Milli Hakimiyet Yerleşkesi No:4/3 PK: 05100 Merkez/AMASYA', 'AMASYA ÜNİVERSİTESİ', 'Devlet', 'Amasya', 'http://www.amasya.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1014, 'https://yokatlas.yok.gov.tr/assets/img/logo/102261.png', 'Anadolu Üniversitesi Yunus Emre Kampusü, 26470 Tepebaşı/ESKİŞEHİR', 'ANADOLU ÜNİVERSİTESİ', 'Devlet', 'Eskişehir', 'http://www.anadolu.edu.tr/', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1015, 'https://yokatlas.yok.gov.tr/assets/img/logo/411762.png', 'Çamlıca Mah.Anadolu Bulv.No:16A/1 Yenimahalle Ankara', 'ANKARA BİLİM ÜNİVERSİTESİ', 'Vakıf', 'Ankara', 'www.ankarabilim.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1016, 'https://yokatlas.yok.gov.tr/assets/img/logo/339985.png', 'Ankara Hacı Bayram Veli Üniversitesi Yüce Tepe Mahallesi 85.Cadde No.8 06570 Çankaya /ANKARA', 'ANKARA HACI BAYRAM VELİ ÜNİVERSİTESİ', 'Devlet', 'Ankara', 'https://hacibayram.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1017, 'https://yokatlas.yok.gov.tr/assets/img/logo/340001.png', 'Hacı Bayram Mahallesi, Talatpaşa Blv. No:2 06050 Altındağ/Ankara', 'ANKARA MEDİPOL ÜNİVERSİTESİ', 'Vakıf', 'Ankara', 'www.ankaramedipol.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1018, 'https://yokatlas.yok.gov.tr/assets/img/logo/324993.png', 'Yukarı Dikmen Mah. Turan Güneş Bul. Neşet Ertaş Cad. No:4 Oran Ankara', 'ANKARA MÜZİK VE GÜZEL SANATLAR ÜNİVERSİTESİ', 'Devlet', 'Ankara', 'http://www.mgu.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1019, 'https://yokatlas.yok.gov.tr/assets/img/logo/232846.png', 'Hükümet Meydanı No: 2 Ulus/ANKARA', 'ANKARA SOSYAL BİLİMLER ÜNİVERSİTESİ', 'Devlet', 'Ankara', 'http://www.asbu.edu.tr/', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1020, 'https://yokatlas.yok.gov.tr/assets/img/logo/102738.png', 'Ankara Üniversitesi Rektörlüğü Tandoğan/ANKARA', 'ANKARA ÜNİVERSİTESİ', 'Devlet', 'Ankara', 'http://www.ankara.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1021, 'https://yokatlas.yok.gov.tr/assets/img/logo/311737.png', 'Ankara Yıldırım Beyazıt Üniversitesi Esenboğa Külliyesi Dumlupınar Mahallesi Çubuk/Ankara', 'ANKARA YILDIRIM BEYAZIT ÜNİVERSİTESİ', 'Devlet', 'Ankara', 'www.aybu.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1022, 'https://yokatlas.yok.gov.tr/assets/img/logo/447662.png', 'Kadriye Mah Celal Bayar CAd No:5-6 Serik-Antalya 07525', 'ANTALYA BELEK ÜNİVERSİTESİ', 'Vakıf', 'Antalya', 'www.belek.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1023, 'https://yokatlas.yok.gov.tr/assets/img/logo/327022.png', 'Çıplaklı Mah. Akdeniz Bulvarı No:290/A Döşemealtı / ANTALYA', 'ANTALYA BİLİM ÜNİVERSİTESİ', 'Vakıf', 'Antalya', 'http://www.antalya.edu.tr/', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1024, 'https://yokatlas.yok.gov.tr/assets/img/logo/103400.png', 'Ardahan Üniversitesi Yenisey Kampüsü, Rektörlük Hizmet Binası, Çamlıçatak Mevkii, 75000, Merkez/Ardahan', 'ARDAHAN ÜNİVERSİTESİ', 'Devlet', 'Ardahan', 'http://www.ardahan.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1025, 'https://yokatlas.yok.gov.tr/assets/img/logo/103443.png', 'Artvin Çoruh Üniversitesi Rektörlüğü Fidanlık Mah.Kapı Nu.110 08000 Seyitler Yerleşkesi-ARTVİN', 'ARTVİN ÇORUH ÜNİVERSİTESİ', 'Devlet', 'Artvin', 'http://www.artvin.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1026, 'https://yokatlas.yok.gov.tr/assets/img/logo/255896.png', 'Yenişehir Mahallesi Barajyolu Caddesi Çağlayan Sokak No:18 Ataşehir / İstanbul', 'ATAŞEHİR ADIGÜZEL MESLEK YÜKSEKOKULU', 'Vakıf', 'İstanbul', 'http://www.adiguzel.edu.tr/', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1027, 'https://yokatlas.yok.gov.tr/assets/img/logo/103545.png', 'Atatürk Üniversitesi Rektörlüğü Yakutiye/Erzurum', 'ATATÜRK ÜNİVERSİTESİ', 'Devlet', 'Erzurum', 'http://www.atauni.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1028, 'https://yokatlas.yok.gov.tr/assets/img/logo/104090.png', 'Atılım Üniversitesi Kızılcaşar Mah. İncek Kampüsü Gölbaşı/İncek/ANKARA', 'ATILIM ÜNİVERSİTESİ', 'Vakıf', 'Ankara', 'www.atilim.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1029, 'https://yokatlas.yok.gov.tr/assets/img/logo/205351.png', 'Avrasya Üniversitesi Rektörlüğü
Adnan Kahvesi Mah. Rize Caddesi
Pelitli/TRABZON', 'AVRASYA ÜNİVERSİTESİ', 'Vakıf', 'Trabzon', 'http://www.avrasya.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1030, 'https://yokatlas.yok.gov.tr/assets/img/logo/364158.png', 'AYTEPE MEVKİ AYDIN', 'AYDIN ADNAN MENDERES ÜNİVERSİTESİ', 'Devlet', 'Aydın', 'http://www.adu.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1031, 'https://yokatlas.yok.gov.tr/assets/img/logo/104140.png', 'Çırağan Caddesi Osmanpaşa Mektebi Sokak No: 4-6 3453 Beşiktaş, İSTANBUL / TÜRKİYE', 'BAHÇEŞEHİR ÜNİVERSİTESİ', 'Vakıf', 'İstanbul', 'http://www.bahcesehir.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1032, 'https://yokatlas.yok.gov.tr/assets/img/logo/104213.png', 'Balıkesir Üniversitesi Çağış Yerleşkesi (Bigadiç yolu üzeri 17. km) 10145, BALIKESİR', 'BALIKESİR ÜNİVERSİTESİ', 'Devlet', 'Balıkesir', 'http://www.balikesir.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1033, 'https://yokatlas.yok.gov.tr/assets/img/logo/274881.png', 'Yeni Mh. Şehit Astsubay Mustafa Soner Varlık Cd. No:77 Bandırma/BALIKESİR', 'BANDIRMA ONYEDİ EYLÜL ÜNİVERSİTESİ', 'Devlet', 'Balıkesir', 'http://www.bandirma.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1034, 'https://yokatlas.yok.gov.tr/assets/img/logo/104578.png', 'Bartın Üniversitesi Rektörlüğü Merkez/BARTIN', 'BARTIN ÜNİVERSİTESİ', 'Devlet', 'Bartın', 'http://www.bartin.edu.tr/', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1035, 'https://yokatlas.yok.gov.tr/assets/img/logo/104628.png', 'Bağlıca Kampüsü Fatih Sultan Mahallesi
Eskişehir Yolu 18.km TR 06790
Etimesgut Ankara', 'BAŞKENT ÜNİVERSİTESİ', 'Vakıf', 'Ankara', 'http://www.baskent.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1036, 'https://yokatlas.yok.gov.tr/assets/img/logo/104803.png', 'Batı Raman 72100 Batman, Türkiye', 'BATMAN ÜNİVERSİTESİ', 'Devlet', 'Batman', 'http://www.batman.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1037, 'https://yokatlas.yok.gov.tr/assets/img/logo/104922.png', 'Dede Korkut Külliyesi 69000 / BAYBURT', 'BAYBURT ÜNİVERSİTESİ', 'Devlet', 'Bayburt', 'https://bayburt.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1038, 'https://yokatlas.yok.gov.tr/assets/img/logo/306383.png', 'Kavacık Mahallesi Orhan Veli Kanık Caddesi No:114 Kavacık Beykoz İstanbul', 'BEYKOZ ÜNİVERSİTESİ', 'Vakıf', 'İstanbul', 'www.beykoz.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1039, 'https://yokatlas.yok.gov.tr/assets/img/logo/163894.png', 'Adnan Menderes Bulvarı Vatan Cad. 34093 Fatih/İSTANBUL', 'BEZM-İ ÂLEM VAKIF ÜNİVERSİTESİ', 'Vakıf', 'İstanbul', 'http://www.bezmialem.edu.tr/', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1040, 'https://yokatlas.yok.gov.tr/assets/img/logo/105024.png', 'Bilecik Şeyh Edebali Üniversitesi Rektörlüğü 11210 Merkez Bilecik', 'BİLECİK ŞEYH EDEBALİ ÜNİVERSİTESİ', 'Devlet', 'Bilecik', 'http://www.bilecik.edu.tr/', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1041, 'https://yokatlas.yok.gov.tr/assets/img/logo/105196.png', 'Selahaddin-i Eyyübi Mah. Üniversite Cad. No:1 BİNGÖL', 'BİNGÖL ÜNİVERSİTESİ', 'Devlet', 'Bingöl', 'http://www.bingol.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1042, 'https://yokatlas.yok.gov.tr/assets/img/logo/251241.png', '10. Yıl Caddesi Protokol Yolu No: 45 (Eski Kozlu Mezarlığı altı, Silivrikapı ve Belgratkapı İett durakları arası) 34010 Topkapı İstanbul', 'BİRUNİ ÜNİVERSİTESİ', 'Vakıf', 'İstanbul', 'http://www.biruni.edu.tr/', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1043, 'https://yokatlas.yok.gov.tr/assets/img/logo/105248.png', 'Rahva Yerleşkesi Beş Minare Mah. Ahmet Eren Bulvarı 13100 Merkez / Bitlis', 'BİTLİS EREN ÜNİVERSİTESİ', 'Devlet', 'Bitlis', 'www.beu.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1044, 'https://yokatlas.yok.gov.tr/assets/img/logo/105322.png', 'Boğaziçi Üniversitesi 
34342 Bebek/Istanbul Türkiye', 'BOĞAZİÇİ ÜNİVERSİTESİ', 'Devlet', 'İstanbul', 'http://www.boun.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1045, 'https://yokatlas.yok.gov.tr/assets/img/logo/341799.png', 'Abant İzzet Baysal Üniversitesi Gölköy Kampüsü 14280 BOLU', 'BOLU ABANT İZZET BAYSAL ÜNİVERSİTESİ', 'Devlet', 'Bolu', 'http://www.ibu.edu.tr/', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1046, 'https://yokatlas.yok.gov.tr/assets/img/logo/355074.png', 'İstiklal Yerleşkesi BURDUR', 'BURDUR MEHMET AKİF ERSOY ÜNİVERSİTESİ', 'Devlet', 'Burdur', 'http://www.mehmetakif.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1047, 'https://yokatlas.yok.gov.tr/assets/img/logo/173494.png', 'Mimar Sinan Mahallesi Mimar Sinan Bulvarı Eflak Caddesi No:177 16310 Yıldırım/BURSA', 'BURSA TEKNİK ÜNİVERSİTESİ', 'Devlet', 'Bursa', 'http://btu.edu.tr/', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1048, 'https://yokatlas.yok.gov.tr/assets/img/logo/362386.png', 'Görükle Kampusu 16059 Nilüfer/BURSA', 'BURSA ULUDAĞ ÜNİVERSİTESİ', 'Devlet', 'Bursa', 'http://www.uludag.edu.tr/', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1049, 'https://yokatlas.yok.gov.tr/assets/img/logo/106499.png', 'Adana-Mersin D 400 Karayolu Üzeri 33800 Yenice-Tarsus/MERSİN', 'ÇAĞ ÜNİVERSİTESİ', 'Vakıf', 'Mersin', 'http://www.cag.edu.tr/', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1050, 'https://yokatlas.yok.gov.tr/assets/img/logo/106545.png', 'Çanakkale Onsekiz Mart Üniversitesi, Terzioğlu Kampüsü, Rektörlük Binası , A Blok  Merkez/ÇANAKKALE', 'ÇANAKKALE ONSEKİZ MART ÜNİVERSİTESİ', 'Devlet', 'Çanakkale', 'www.comu.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1051, 'https://yokatlas.yok.gov.tr/assets/img/logo/107012.png', 'Çankaya Üniversitesi  Merkez Kampüs : Eskişehir Yolu 29. Km Yukarıyurtçu Mahallesi, Mimar Sinan Caddesi No:4, 06790, Etimesgut / ANKARA', 'ÇANKAYA ÜNİVERSİTESİ', 'Vakıf', 'Ankara', 'http://www.cankaya.edu.tr/', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1052, 'https://yokatlas.yok.gov.tr/assets/img/logo/107056.png', 'Uluyazı Kampüsü Binası / Çankırı', 'ÇANKIRI KARATEKİN ÜNİVERSİTESİ', 'Devlet', 'Çankırı', 'www.karatekin.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1053, 'https://yokatlas.yok.gov.tr/assets/img/logo/107211.png', 'Çukurova Üniversitesi Rektörlüğü 01330 Balcalı, Sarıçam / ADANA', 'ÇUKUROVA ÜNİVERSİTESİ', 'Devlet', 'Adana', 'www.cu.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1054, 'https://yokatlas.yok.gov.tr/assets/img/logo/384591.png', 'Büyükdere Cad. No:120 Esentepe-Şişli İSTANBUL', 'DEMİROĞLU BİLİM ÜNİVERSİTESİ', 'Vakıf', 'İstanbul', 'http://www.demiroglu.bilim.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1055, 'https://yokatlas.yok.gov.tr/assets/img/logo/107723.png', '21280 Kıtılbil Mahallesi Sur / Diyarbakır', 'DİCLE ÜNİVERSİTESİ', 'Devlet', 'Diyarbakır', 'www.dicle.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1056, 'https://yokatlas.yok.gov.tr/assets/img/logo/108112.png', 'Doğuş Üniversitesi Zeamet sk. 34722 Kadıköy/İstanbul', 'DOĞUŞ ÜNİVERSİTESİ', 'Vakıf', 'İstanbul', 'http://www.dogus.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1057, 'https://yokatlas.yok.gov.tr/assets/img/logo/108163.png', 'Cumhuriyet Bulvarı No:144 Alsancak 35210 Konak/İZMİR', 'DOKUZ EYLÜL ÜNİVERSİTESİ', 'Devlet', 'İzmir', 'http://www.deu.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1058, 'https://yokatlas.yok.gov.tr/assets/img/logo/109110.png', 'Düzce Üniversitesi Rektörlüğü Genel Sekreterlik Beçi Kampüsü Merkez Düzce', 'DÜZCE ÜNİVERSİTESİ', 'Devlet', 'Düzce', 'http://www.duzce.edu.tr/', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1059, 'https://yokatlas.yok.gov.tr/assets/img/logo/109290.png', 'Ege Üniversitesi Rektörlüğü Gençlik Caddesi No:12 PK.35040 Bornova / İzmir', 'EGE ÜNİVERSİTESİ', 'Devlet', 'İzmir', 'http://www.ege.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1060, 'https://yokatlas.yok.gov.tr/assets/img/logo/109868.png', 'Talas Yolu Melikgazi 38039 KAYSERİ', 'ERCİYES ÜNİVERSİTESİ', 'Devlet', 'Kayseri', 'http://www.erciyes.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1061, 'https://yokatlas.yok.gov.tr/assets/img/logo/370189.png', 'Erzincan Binali Yıldırım Üniversitesi Rektörlüğü  Yalnızbağ Yerleşkesi- Erzincan/Merkez', 'ERZİNCAN BİNALİ YILDIRIM ÜNİVERSİTESİ', 'Devlet', 'Erzincan', 'http://www.erzincan.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1062, 'https://yokatlas.yok.gov.tr/assets/img/logo/173495.png', 'ERZURUM TEKNİK ÜNİVERSİTESİ Ömer Nasuhi Bilmen Mah. Havaalanı Yolu Cad. No:53 YAKUTİYE/ERZURUM', 'ERZURUM TEKNİK ÜNİVERSİTESİ', 'Devlet', 'Erzurum', 'http://www.erzurum.edu.tr/', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1063, 'https://yokatlas.yok.gov.tr/assets/img/logo/110538.png', 'Eskişehir Osmangazi Üniversitesi Meşelik Kampüsü Büyükdere Mahallesi Prof.Dr.Nabi AVCI Bulvarı No:4 26040 Eskişehir', 'ESKİŞEHİR OSMANGAZİ ÜNİVERSİTESİ', 'Devlet', 'Eskişehir', 'http://www.ogu.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1064, 'https://yokatlas.yok.gov.tr/assets/img/logo/339997.png', 'Eskişehir Teknik Üniversitesi 
İki Eylül Kampüsü 26555 Tepebaşı/ESKİŞEHİR', 'ESKİŞEHİR TEKNİK ÜNİVERSİTESİ', 'Devlet', 'Eskişehir', 'https://www.eskisehir.edu.tr/', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1065, 'https://yokatlas.yok.gov.tr/assets/img/logo/163897.png', 'Zeyrek Mah. Büyük karaman Cad. No:53 FATİH/ İSTANBUL', 'FATİH SULTAN MEHMET VAKIF ÜNİVERSİTESİ', 'Vakıf', 'İstanbul', 'www.fsm.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1066, 'https://yokatlas.yok.gov.tr/assets/img/logo/310017.png', 'Atatürk Mah. Ataşehir Bulvarı Ertuğrul Gazi Sk. Metropol İstanbul E Blok, 34758 Ataşehir-İstanbul', 'FENERBAHÇE ÜNİVERSİTESİ', 'Vakıf', 'İstanbul', 'www.fbu.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1067, 'https://yokatlas.yok.gov.tr/assets/img/logo/110987.png', 'Fırat Üniversitesi Rektörlüğü 23119 ELAZIĞ', 'FIRAT ÜNİVERSİTESİ', 'Devlet', 'Elazığ', 'http://www.firat.edu.tr/', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1068, 'https://yokatlas.yok.gov.tr/assets/img/logo/111395.png', 'Galatasaray Üniversitesi Çırağan Cad. No:36 34349 Ortaköy/İstanbul', 'GALATASARAY ÜNİVERSİTESİ', 'Devlet', 'İstanbul', 'http://www.gsu.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1069, 'https://yokatlas.yok.gov.tr/assets/img/logo/133520.png', 'Gazi Üniversitesi Rektörlüğü 06500 Teknikokullar / Ankara', 'GAZİ ÜNİVERSİTESİ', 'Devlet', 'Ankara', 'http://gazi.edu.tr/', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1070, 'https://yokatlas.yok.gov.tr/assets/img/logo/384577.png', 'Beştepe Mah. 192090 Nolu Cadde 6/1 27010 Şahinbey/Gaziantep', 'GAZİANTEP İSLAM BİLİM VE TEKNOLOJİ ÜNİVERSİTESİ', 'Devlet', 'Gaziantep', 'http://www.gibtu.edu.tr/', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1071, 'https://yokatlas.yok.gov.tr/assets/img/logo/112080.png', 'GAZİANTEP ÜNİVERSİTESİ REKTÖRLÜĞÜ', 'GAZİANTEP ÜNİVERSİTESİ', 'Devlet', 'Gaziantep', 'http://www.gantep.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1072, 'https://yokatlas.yok.gov.tr/assets/img/logo/260621.png', 'Gebze Teknik Üniversitesi Rektörlüğü Cumhuriyet Mah. 2254 Sok. No:2 Gebze/KOCAELİ', 'GEBZE TEKNİK ÜNİVERSİTESİ', 'Devlet', 'Kocaeli', 'www.gtu.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1073, 'https://yokatlas.yok.gov.tr/assets/img/logo/112836.png', 'Giresun Üniversitesi | Giresun', 'GİRESUN ÜNİVERSİTESİ', 'Devlet', 'Giresun', 'http://www.giresun.edu.tr/', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1074, 'https://yokatlas.yok.gov.tr/assets/img/logo/113023.png', 'Gümüşhane Üniversitesi Rektörlüğü
Bağlarbaşı Mh.
29000, Merkez/GÜMÜŞHANE', 'GÜMÜŞHANE ÜNİVERSİTESİ', 'Devlet', 'Gümüşhane', 'http://www.gumushane.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1075, 'https://yokatlas.yok.gov.tr/assets/img/logo/113082.png', 'Hacettepe Üniversitesi Rektörlüğü Sıhhıye/ANKARA', 'HACETTEPE ÜNİVERSİTESİ', 'Devlet', 'Ankara', 'http://hacettepe.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1076, 'https://yokatlas.yok.gov.tr/assets/img/logo/113681.png', 'Merzan Mah. Küçük Sanayi Sitesi arkası Merkez/HAKKARİ', 'HAKKARİ ÜNİVERSİTESİ', 'Devlet', 'Hakkari', 'www.hakkari.edu.tr / www.hu.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1077, 'https://yokatlas.yok.gov.tr/assets/img/logo/113699.png', 'Sütlüce Mahallesi, İmrahor Caddesi, No:11, Beyoğlu, istanbul', 'HALİÇ ÜNİVERSİTESİ', 'Vakıf', 'İstanbul', 'www.halic.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1078, 'https://yokatlas.yok.gov.tr/assets/img/logo/113746.png', 'Harran Üniversitesi Rektörlüğü Osmanbey Kampüsü Şanlıurfa', 'HARRAN ÜNİVERSİTESİ', 'Devlet', 'Şanlıurfa', 'http://www.harran.edu.tr/', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1079, 'https://yokatlas.yok.gov.tr/assets/img/logo/138586.png', 'Yeşilkent Mah. Havalimanı Yolu üzeri 8.km Şahinbey/GAZİANTEP', 'HASAN KALYONCU ÜNİVERSİTESİ', 'Vakıf', 'Gaziantep', 'www.hku.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1080, 'https://yokatlas.yok.gov.tr/assets/img/logo/367208.png', 'Alahan Tayfur Sökmen Kampüsü Dış kapı no:35 Adres No:3330417886 Alahan/Antakya/Hatay', 'HATAY MUSTAFA KEMAL ÜNİVERSİTESİ', 'Devlet', 'Hatay', 'http://www.mku.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1081, 'https://yokatlas.yok.gov.tr/assets/img/logo/114218.png', 'Hitit Üniversitesi Kuzey Kampüsü Çevre Yolu Bulvarı PK:19030 ÇORUM', 'HİTİT ÜNİVERSİTESİ', 'Devlet', 'Çorum', 'http://www.hitit.edu.tr/', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1082, 'https://yokatlas.yok.gov.tr/assets/img/logo/114315.png', 'Şehit Bülent Yurtseven Kampüsü/ IĞDIR', 'IĞDIR ÜNİVERSİTESİ', 'Devlet', 'Iğdır', 'http://www.igdir.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1083, 'https://yokatlas.yok.gov.tr/assets/img/logo/339998.png', 'Isparta uygulamalı Bilimler Üniversitesi Rektörlüğü, Bahçelievler Mah., 102. Cad., No:24, 32200, ISPARTA', 'ISPARTA UYGULAMALI BİLİMLER ÜNİVERSİTESİ', 'Devlet', 'Isparta', 'https://isparta.edu.tr/', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1084, 'https://yokatlas.yok.gov.tr/assets/img/logo/114385.png', 'Işık Üniversitesi, Meşrutiyet Köyü, Üniversitesi Sok. No:2 ŞİLE/İSTANBUL', 'IŞIK ÜNİVERSİTESİ', 'Vakıf', 'İstanbul', 'http://www.isikun.edu.tr/', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1085, 'https://yokatlas.yok.gov.tr/assets/img/logo/274887.png', 'Başak Mah. Ordu Cad. F-05 Blok No:3 P.K. 34480 Başakşehir/İST.', 'İBN HALDUN ÜNİVERSİTESİ', 'Vakıf', 'İstanbul', 'www.ihu.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1086, 'https://yokatlas.yok.gov.tr/assets/img/logo/105118.png', 'Üniversiteler Mahallesi 1609 Sokak No:10 06800 Bilkent / Ankara', 'İHSAN DOĞRAMACI BİLKENT ÜNİVERSİTESİ', 'Vakıf', 'Ankara', 'http://www.bilkent.edu.tr/', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1087, 'https://yokatlas.yok.gov.tr/assets/img/logo/114436.png', 'İnönü Üniversitesi Kampüsü Elazığ Yolu 15. Km. 44280 MALATYA', 'İNÖNÜ ÜNİVERSİTESİ', 'Devlet', 'Malatya', 'http://www.inonu.edu.tr/', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1088, 'https://yokatlas.yok.gov.tr/assets/img/logo/274882.png', 'İskenderun Teknik Üniversitesi Rektörlüğü Merkez Kampüs 31200 
İskenderun/HATAY', 'İSKENDERUN TEKNİK ÜNİVERSİTESİ', 'Devlet', 'Hatay', 'www.iste.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1089, 'https://yokatlas.yok.gov.tr/assets/img/logo/163900.png', 'Elmalıkent Mah. Elmalıkent Cad. No:4
Ümraniye / İSTANBUL', 'İSTANBUL 29 MAYIS ÜNİVERSİTESİ', 'Vakıf', 'İstanbul', 'http://www.29mayis.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1090, 'https://yokatlas.yok.gov.tr/assets/img/logo/114773.png', 'İstanbul Arel Üniversitesi -Türkoba Mah. Erguvan Sokak No: 26/K Tepekent-B.Çekmece/İSTANBUL', 'İSTANBUL AREL ÜNİVERSİTESİ', 'Vakıf', 'İstanbul', 'http://www.arel.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1091, 'https://yokatlas.yok.gov.tr/assets/img/logo/339995.png', 'Hamidiye Mahallesi Anadolu Caddesi No:40/2 Kağıthane/İSTANBUL', 'İSTANBUL ATLAS ÜNİVERSİTESİ', 'Vakıf', 'İstanbul', 'www.atlas.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1092, 'https://yokatlas.yok.gov.tr/assets/img/logo/114827.png', 'Florya Halit Aydın Kampüsü Beşyol Mah. İnönü Cad. No: 38 Sefaköy-Küçükçekmece/İSTANBUL', 'İSTANBUL AYDIN ÜNİVERSİTESİ', 'Vakıf', 'İstanbul', 'http://www.aydin.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1093, 'https://yokatlas.yok.gov.tr/assets/img/logo/448766.png', 'Ayazağa Mahallesi, Hadım Koru Yolu Caddesi, No:19 Sarıyer/İSTANBUL', 'İSTANBUL BEYKENT ÜNİVERSİTESİ', 'Vakıf', 'İstanbul', 'www.beykent.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1094, 'https://yokatlas.yok.gov.tr/assets/img/logo/114907.png', 'Eski Silahtarağa Elektrik Santralı Kazım Karabekir Cad. No: 2/13 34060 Eyüpsultan İstanbul', 'İSTANBUL BİLGİ ÜNİVERSİTESİ', 'Vakıf', 'İstanbul', 'www.bilgi.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1095, 'https://yokatlas.yok.gov.tr/assets/img/logo/241174.png', 'Zafer Mah. Adile Naşit Bulvarı No:1 Esenyurt-İSTANBUL', 'İSTANBUL ESENYURT ÜNİVERSİTESİ', 'Vakıf', 'İstanbul', 'http://www.esenyurt.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1096, 'https://yokatlas.yok.gov.tr/assets/img/logo/391144.png', 'Evliya Çelebi Mahallesi Meşrutiyet Caddesi No: 62 Tepebaşı/Beyoğlu/İstanbul', 'İSTANBUL GALATA ÜNİVERSİTESİ', 'Vakıf', 'İstanbul', 'www.galata.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1097, 'https://yokatlas.yok.gov.tr/assets/img/logo/315098.png', 'Cumhuriyet Mahallesi İlkbahar Sokak No: 1 Yakacık 34876 Kartal İstanbul', 'İSTANBUL GEDİK ÜNİVERSİTESİ', 'Vakıf', 'İstanbul', 'www.gedik.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1098, 'https://yokatlas.yok.gov.tr/assets/img/logo/130959.png', 'Cihangir Mahallesi Şehit Jandarma Komando Er Hakan Öner Sk. No:1 Avcılar / İSTANBUL', 'İSTANBUL GELİŞİM ÜNİVERSİTESİ', 'Vakıf', 'İstanbul', 'www.gelisim.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1099, 'https://yokatlas.yok.gov.tr/assets/img/logo/302687.png', 'Cihangir Mahallesi Sıraselviler Caddesi No:71 34433 Beyoğlu İSTANBUL', 'İSTANBUL KENT ÜNİVERSİTESİ', 'Vakıf', 'İstanbul', 'www.kent.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1100, 'https://yokatlas.yok.gov.tr/assets/img/logo/115022.png', 'Ataköy Yerleşkesi, 34156 Bakırköy / İSTANBUL', 'İSTANBUL KÜLTÜR ÜNİVERSİTESİ', 'Vakıf', 'İstanbul', 'www.iku.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1101, 'https://yokatlas.yok.gov.tr/assets/img/logo/173496.png', 'Dumlupınar mahallesi, D-100 Karayolu No:98  Kadıköy / İstanbul', 'İSTANBUL MEDENİYET ÜNİVERSİTESİ', 'Devlet', 'İstanbul', 'http://www.medeniyet.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1102, 'https://yokatlas.yok.gov.tr/assets/img/logo/163888.png', 'Kavacık Mah.Ekinciler Cad.No:19, 34840 Beykoz-İstanbul', 'İSTANBUL MEDİPOL ÜNİVERSİTESİ', 'Vakıf', 'İstanbul', 'www.medipol.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1103, 'https://yokatlas.yok.gov.tr/assets/img/logo/447904.png', 'Maslak Mahallesi, Taşyoncası Sokak,
No: 1V ve No:1Y Bina Kodu: 34481742
Sarıyer/İstanbul', 'İSTANBUL NİŞANTAŞI ÜNİVERSİTESİ', 'Vakıf', 'İstanbul', 'http://www.nisantasi.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1104, 'https://yokatlas.yok.gov.tr/assets/img/logo/360777.png', 'Okan Üniversitesi Tuzla Kampüsü, 34959 Akfırat - Tuzla / İSTANBUL', 'İSTANBUL OKAN ÜNİVERSİTESİ', 'Vakıf', 'İstanbul', 'www.okan.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1105, 'https://yokatlas.yok.gov.tr/assets/img/logo/274886.png', 'Yeni Mahalle Mah. Mehmet Silivrili Cad. No: 38/8 Posta Kodu 34570
SİLİVRİ-İSTANBUL', 'İSTANBUL RUMELİ ÜNİVERSİTESİ', 'Vakıf', 'İstanbul', 'www.rumeli.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1106, 'https://yokatlas.yok.gov.tr/assets/img/logo/163898.png', 'Halkalı Cad. No: 281 Halkalı - Küçükçekmece / İSTANBUL Posta Kodu: 34303', 'İSTANBUL SABAHATTİN ZAİM ÜNİVERSİTESİ', 'Vakıf', 'İstanbul', 'http://www.izu.edu.tr/', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1107, 'https://yokatlas.yok.gov.tr/assets/img/logo/432690.png', 'Cankurtaran Mahallesi Kennedy Caddesi No:2 Ahırkapı Feneri Yanı Fatih İSTANBUL', 'İSTANBUL SAĞLIK VE SOSYAL BİLİMLER MESLEK YÜKSEKOKULU', 'Vakıf', 'İstanbul', 'www.issb.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1108, 'https://yokatlas.yok.gov.tr/assets/img/logo/410560.png', 'Sütlüce Kampüsü
Sütlüce Mah. İmrahor Cad. No: 82
Beyoğlu – İstanbul', 'İSTANBUL SAĞLIK VE TEKNOLOJİ ÜNİVERSİTESİ', 'Vakıf', 'İstanbul', 'www.istun.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1109, 'https://yokatlas.yok.gov.tr/assets/img/logo/220121.png', 'Maslak Mah. Atatürk Oto Sanayi Sitesi 55. Sok. No:2 Sarıyer/ İSTANBUL', 'İSTANBUL ŞİŞLİ MESLEK YÜKSEKOKULU', 'Vakıf', 'İstanbul', 'www.sisli.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1110, 'https://yokatlas.yok.gov.tr/assets/img/logo/115069.png', 'İTÜ Ayazağa Yerleşkesi yeni Rektörlük Binası Kat:2 MASLAK-SARIYER-İSTANBUL', 'İSTANBUL TEKNİK ÜNİVERSİTESİ', 'Devlet', 'İstanbul', 'http://www.itu.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1111, 'https://yokatlas.yok.gov.tr/assets/img/logo/115335.png', 'Örnektepe Mahallesi, İmrahor Caddesi No: 88/2 34445 Beyoğlu / İSTANBUL', 'İSTANBUL TİCARET ÜNİVERSİTESİ', 'Vakıf', 'İstanbul', 'http://www.ticaret.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1112, 'https://yokatlas.yok.gov.tr/assets/img/logo/440213.png', 'Prof.Muammer Aksoy Cd. No: 10 Kazlıçeşme / İSTANBUL', 'İSTANBUL TOPKAPI ÜNİVERSİTESİ', 'Vakıf', 'İstanbul', 'www.topkapi.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1113, 'https://yokatlas.yok.gov.tr/assets/img/logo/115373.png', 'İSTANBUL ÜNİVERSİTESİ REKTÖRLÜK
İSTANBUL UNIVERSITY RECTORATE
İstanbul Üniversitesi, Beyazıt Yerleşkesi
34452 Beyazıt, İstanbul – Türkiye', 'İSTANBUL ÜNİVERSİTESİ', 'Devlet', 'İstanbul', 'http://www.istanbul.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1114, 'https://yokatlas.yok.gov.tr/assets/img/logo/339984.png', 'İstanbul Üniversitesi-Cerrahpaşa Rektörlüğü 34320 Avcılar/İstanbul', 'İSTANBUL ÜNİVERSİTESİ-CERRAHPAŞA', 'Devlet', 'İstanbul', 'https://iuc.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1115, 'https://yokatlas.yok.gov.tr/assets/img/logo/315415.png', 'T.C. İstanbul Yeni Yüzyıl Üniversitesi
Topkapı Dr. Azmi  Ofluoğlu Yerleşkesi
Maltepe Mahallesi, Yılanlı Ayazma Caddesi No:26, 34010 Cevizlibağ- Zeytinburnu / İSTANBUL', 'İSTANBUL YENİ YÜZYIL ÜNİVERSİTESİ', 'Vakıf', 'İstanbul', 'www.yeniyuzyil.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1116, 'https://yokatlas.yok.gov.tr/assets/img/logo/274888.png', 'İstinye Üniversitesi Topkapı Kampüsü, Maltepe Mah., Teyyareci Sami Sokak, No.3 Zeytinburnu, İstanbul, 34010', 'İSTİNYE ÜNİVERSİTESİ', 'Vakıf', 'İstanbul', 'www.istinye.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1117, 'https://yokatlas.yok.gov.tr/assets/img/logo/302686.png', 'Seyrek Kampüsü/ Gazi Mustafa Kemal Mah.Kaynaklar Cad./ Seyrek/Menemen/İZMİR', 'İZMİR BAKIRÇAY ÜNİVERSİTESİ', 'Devlet', 'İzmir', 'bakircay.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1118, 'https://yokatlas.yok.gov.tr/assets/img/logo/302685.png', 'Üçkuyular Mahallesi, Gürsel Aksel Bulvarı, No:14 35140 Karabağlar/İZMİR', 'İZMİR DEMOKRASİ ÜNİVERSİTESİ', 'Devlet', 'İzmir', 'http://www.idu.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1119, 'https://yokatlas.yok.gov.tr/assets/img/logo/116147.png', 'SAKARYA CAD. NO:156 BALÇOVA/İZMİR', 'İZMİR EKONOMİ ÜNİVERSİTESİ', 'Vakıf', 'İzmir', 'www.ieu.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1120, 'https://yokatlas.yok.gov.tr/assets/img/logo/173498.png', 'İzmir Kâtip Çelebi Üniversitesi Çiğli Ana Yerleşkesi
35620 İZMİR', 'İZMİR KATİP ÇELEBİ ÜNİVERSİTESİ', 'Devlet', 'İzmir', 'http://www.ikc.edu.tr/', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1121, 'https://yokatlas.yok.gov.tr/assets/img/logo/334490.png', 'Oğuzlar Mah. 1251/2 Sok. No:8 Konak/İzmir', 'İZMİR KAVRAM MESLEK YÜKSEKOKULU', 'Vakıf', 'İzmir', 'www.kavram.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1122, 'https://yokatlas.yok.gov.tr/assets/img/logo/339996.png', 'Aydoğdu Mahallesi, 1267/1 Sk., No.4 35400 Buca/İzmir', 'İZMİR TINAZTEPE ÜNİVERSİTESİ', 'Vakıf', 'İzmir', 'www.tinaztepe.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1123, 'https://yokatlas.yok.gov.tr/assets/img/logo/116207.png', 'İzmir Yüksek Teknoloji Enstitüsü Gülbahçe Kampüsü Urla/İZMİR', 'İZMİR YÜKSEK TEKNOLOJİ ENSTİTÜSÜ', 'Devlet', 'İzmir', 'http://www.iyte.edu.tr/', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1124, 'https://yokatlas.yok.gov.tr/assets/img/logo/116281.png', 'Kadir Has Üniversitesi, Kadir Has Caddesi,
Cibali / İSTANBUL 34083', 'KADİR HAS ÜNİVERSİTESİ', 'Vakıf', 'İstanbul', 'http://www.khas.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1125, 'https://yokatlas.yok.gov.tr/assets/img/logo/116345.png', 'Kafkas Üniversitesi Şehitler Mh. Turan Çelik Cd. Kombina Yolu Üzeri Merkez/KARS', 'KAFKAS ÜNİVERSİTESİ', 'Devlet', 'Kars', 'http://www.kafkas.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1126, 'https://yokatlas.yok.gov.tr/assets/img/logo/339994.png', 'Kahramanmaraş İstiklal Üniversitesi Rektörlüğü, Menderes Mah. Cumhuriyet Bulvarı 46036 Sokak No:7 46060 Dulkadiroğlu/Kahramanmaraş', 'KAHRAMANMARAŞ İSTİKLAL ÜNİVERSİTESİ', 'Devlet', 'Kahramanmaraş', 'www.istiklal.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1127, 'https://yokatlas.yok.gov.tr/assets/img/logo/116608.png', 'Kahramanmaraş Sütçü İmam Üniversitesi Rektörlüğü,  Avşar Mah. Batı Çevreyolu Blv.  No: 251/A 46040 - Onikişubat/Kahramanmaraş', 'KAHRAMANMARAŞ SÜTÇÜ İMAM ÜNİVERSİTESİ', 'Devlet', 'Kahramanmaraş', 'www.ksu.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1128, 'https://yokatlas.yok.gov.tr/assets/img/logo/325756.png', 'Üniversite Meydanı No:2 Mustafapaşa Ürgüp/Nevşehir', 'KAPADOKYA ÜNİVERSİTESİ', 'Vakıf', 'Nevşehir', 'www.kapadokya.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1129, 'https://yokatlas.yok.gov.tr/assets/img/logo/116950.png', 'Karabük Üniversitesi Demir Çelik Kampüsü Balıklar Kaya Mevkii', 'KARABÜK ÜNİVERSİTESİ', 'Devlet', 'Karabük', 'http://www.karabuk.edu.tr/', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1130, 'https://yokatlas.yok.gov.tr/assets/img/logo/117127.png', 'Karadeniz Teknik Üniversitesi
61080 - Trabzon', 'KARADENİZ TEKNİK ÜNİVERSİTESİ', 'Devlet', 'Trabzon', 'http://www.ktu.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1131, 'https://yokatlas.yok.gov.tr/assets/img/logo/117553.png', 'Karamanoğlu Mehmetbey Üniversitesi, Yunus Emre Yerleşkesi, 70100 KARAMAN / TÜRKİYE', 'KARAMANOĞLU MEHMETBEY ÜNİVERSİTESİ', 'Devlet', 'Karaman', 'http://www.kmu.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1132, 'https://yokatlas.yok.gov.tr/assets/img/logo/117673.png', 'Kastamonu Üniversitesi Rektörlüğü Kuzeykent Kampüsü Merkez/KASTAMONU', 'KASTAMONU ÜNİVERSİTESİ', 'Devlet', 'Kastamonu', 'http://www.kastamonu.edu.tr/index.php/tr/', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1133, 'https://yokatlas.yok.gov.tr/assets/img/logo/339993.png', 'Mevlana Mah. 15 Temmuz Yerleşkesi Kümeevler Talas/KAYSERİ', 'KAYSERİ ÜNİVERSİTESİ', 'Devlet', 'Kayseri', 'http://www.kayseri.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1134, 'https://yokatlas.yok.gov.tr/assets/img/logo/117803.png', 'Kırıkkale Üniversitesi Ankara Yolu 7. Km 71450 Yahşihan/Kırıkkale', 'KIRIKKALE ÜNİVERSİTESİ', 'Devlet', 'Kırıkkale', 'http://kku.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1135, 'https://yokatlas.yok.gov.tr/assets/img/logo/118122.png', 'Cumhuriyet Mahallesi Kofcaz Yolu
Kayalı Yerleşkesi Merkez-Kırklareli', 'KIRKLARELİ ÜNİVERSİTESİ', 'Devlet', 'Kırklareli', 'http://www.klu.edu.tr/', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1136, 'https://yokatlas.yok.gov.tr/assets/img/logo/354265.png', 'Bağbaşı Mah. Sahir Kurutluoğlu Cad. No: 100 Merkez/KIRŞEHİR', 'KIRŞEHİR AHİ EVRAN ÜNİVERSİTESİ', 'Devlet', 'Kırşehir', 'www.ahievran.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1137, 'https://yokatlas.yok.gov.tr/assets/img/logo/118186.png', 'Mehmet Sanlı Mah. Doğan Güreş Paşa Bulvarı No.134 Merlez/KİLİS', 'KİLİS 7 ARALIK ÜNİVERSİTESİ', 'Devlet', 'Kilis', 'www.kilis.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1138, 'https://yokatlas.yok.gov.tr/assets/img/logo/411763.png', 'Yeniköy Merkez Mh. Ilıca Cd. No:29 Başiskele/KOCAELİ', 'KOCAELİ SAĞLIK VE TEKNOLOJİ ÜNİVERSİTESİ', 'Vakıf', 'Kocaeli', 'www.kocaelisaglik.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1139, 'https://yokatlas.yok.gov.tr/assets/img/logo/118239.png', 'Umuttepe Merkez Yerleşkesi 41380 İzmit/KOCAELİ', 'KOCAELİ ÜNİVERSİTESİ', 'Devlet', 'Kocaeli', 'http://www.kocaeli.edu.tr/', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1140, 'https://yokatlas.yok.gov.tr/assets/img/logo/118853.png', 'Koç Üniversitesi, Rumelifeneri Yolu, 34450, SARIYER, ISTANBUL', 'KOÇ ÜNİVERSİTESİ', 'Vakıf', 'İstanbul', 'http://www.ku.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1141, 'https://yokatlas.yok.gov.tr/assets/img/logo/241176.png', 'Melikşah Mah. Beyşehir Cad. No:9 42080 Meram / KONYA', 'KONYA GIDA VE TARIM ÜNİVERSİTESİ', 'Vakıf', 'Konya', 'http://www.gidatarim.edu.tr/', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1142, 'https://yokatlas.yok.gov.tr/assets/img/logo/339979.png', 'Akademi Mah. Yeni İstanbul Cad. No:235/1 Selçuklu/KONYA', 'KONYA TEKNİK ÜNİVERSİTESİ', 'Devlet', 'Konya', 'http://www.ktun.edu.tr/', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1143, 'https://yokatlas.yok.gov.tr/assets/img/logo/166433.png', 'KTO Karatay Üniversitesi Rektörlüğü Akabe Mah. Alaaddin Kap Cad. No: 130 Karatay/KONYA', 'KTO KARATAY ÜNİVERSİTESİ', 'Vakıf', 'Konya', 'http://www.karatay.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1144, 'https://yokatlas.yok.gov.tr/assets/img/logo/351149.png', 'Kütahya Dumlupınar Üniversitesi Evliya Çelebi Yerleşkesi Tavşanlı Yolu 10. km.     KÜTAHYA', 'KÜTAHYA DUMLUPINAR ÜNİVERSİTESİ', 'Devlet', 'Kütahya', 'http://dpu.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1145, 'https://yokatlas.yok.gov.tr/assets/img/logo/339982.png', 'Alipaşa Mahallesi Fatih Sultan Mehmet Bulvarı No./22 Kütahya Merkez', 'KÜTAHYA SAĞLIK BİLİMLERİ ÜNİVERSİTESİ', 'Devlet', 'Kütahya', 'http://www.ksbu.edu.tr/', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1146, 'https://yokatlas.yok.gov.tr/assets/img/logo/332474.png', 'Söğütözü Mah. 2179. Cad. No:6 Çankaya Ankara', 'LOKMAN HEKİM ÜNİVERSİTESİ', 'Vakıf', 'Ankara', 'www.lokmanhekim.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1147, 'https://yokatlas.yok.gov.tr/assets/img/logo/339983.png', 'Alacakapı Mahallesi Kırkgöz Caddesi No:70 P.K. 44210 Battalgazi / MALATYA', 'MALATYA TURGUT ÖZAL ÜNİVERSİTESİ', 'Devlet', 'Malatya', 'www.ozal.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1148, 'https://yokatlas.yok.gov.tr/assets/img/logo/118883.png', 'Maltepe Üniversitesi Marmara Eğitim Köyü PK:34857 MALTEPE İSTANBUL', 'MALTEPE ÜNİVERSİTESİ', 'Vakıf', 'İstanbul', 'http://www.maltepe.edu.tr/', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1149, 'https://yokatlas.yok.gov.tr/assets/img/logo/315839.png', 'Şehit Prof. Dr. İlhan Varank Kampüsü 45140 - Yunusemre - MANİSA', 'MANİSA CELÂL BAYAR ÜNİVERSİTESİ', 'Devlet', 'Manisa', 'www.cbu.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1150, 'https://yokatlas.yok.gov.tr/assets/img/logo/118994.png', 'Mardin Artuklu Üniversitesi Yenişehir Yerleşkesi, Diyarbakır Yolu
Yenişehir Mardin', 'MARDİN ARTUKLU ÜNİVERSİTESİ', 'Devlet', 'Mardin', 'http://www.artuklu.edu.tr/', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1151, 'https://yokatlas.yok.gov.tr/assets/img/logo/119094.png', 'M.Ü.Göztepe Kampüsü Rektörlük Binası 34722 Kadıköy / İSTANBUL', 'MARMARA ÜNİVERSİTESİ', 'Devlet', 'İstanbul', 'http://www.marmara.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1152, 'https://yokatlas.yok.gov.tr/assets/img/logo/215913.png', 'Ayazağa Cad. No.4 34396
Maslak - Sarıyer - İstanbul', 'MEF ÜNİVERSİTESİ', 'Vakıf', 'İstanbul', 'http://www.mef.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1153, 'https://yokatlas.yok.gov.tr/assets/img/logo/119917.png', 'Mersin Üniversitesi Çiftlikköy Kampusu Rektörlük Binası 33343 Yenişehir/MERSİN', 'MERSİN ÜNİVERSİTESİ', 'Devlet', 'Mersin', 'http://www.mersin.edu.tr/idari/genel-sekreterlik', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1154, 'https://yokatlas.yok.gov.tr/assets/img/logo/120301.png', 'Meclis-i Mebusan Caddesi No: 24
Fındıklı 34427 İstanbul', 'MİMAR SİNAN GÜZEL SANATLAR ÜNİVERSİTESİ', 'Devlet', 'İstanbul', 'https://www.msgsu.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1155, 'https://yokatlas.yok.gov.tr/assets/img/logo/442563.png', 'Çağrışan Mah. 2029 Sk. No:2 16265 Mudanya/Bursa', 'MUDANYA ÜNİVERSİTESİ', 'Vakıf', 'Bursa', 'https://mudanya.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1156, 'https://yokatlas.yok.gov.tr/assets/img/logo/120444.png', 'Muğla Sıtkı Koçman Üniversitesi Rektörlüğü 48000 Menteşe/MUĞLA', 'MUĞLA SITKI KOÇMAN ÜNİVERSİTESİ', 'Devlet', 'Muğla', 'http://www.mu.edu.tr/', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1157, 'https://yokatlas.yok.gov.tr/assets/img/logo/307919.png', 'Aktuluk Mahallesi Üniversite Yerleşkesi Merkez/TUNCELİ', 'MUNZUR ÜNİVERSİTESİ', 'Devlet', 'Tunceli', 'www.munzur.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1158, 'https://yokatlas.yok.gov.tr/assets/img/logo/121164.png', 'Muş Alparslan Üniversitesi Kampusu, Rektörlük, Diyarbakır Yolu 7. km 49250- MUŞ', 'MUŞ ALPARSLAN ÜNİVERSİTESİ', 'Devlet', 'Muş', 'www.alparslan.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1159, 'https://yokatlas.yok.gov.tr/assets/img/logo/173500.png', 'Yaka Mah. Yeni Meram Cad. Kasım Halife Sok. No: 11 (A Blok) Posta Kodu: 42090 Meram / KONYA', 'NECMETTİN ERBAKAN ÜNİVERSİTESİ', 'Devlet', 'Konya', 'http://www.erbakan.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1160, 'https://yokatlas.yok.gov.tr/assets/img/logo/246224.png', 'Nevşehir Hacı Bektaş Veli Üniversitesi Rektörlüğü 
2000 Evler Mahallesi Zübeyde Hanım Cad. 50300
NEVŞEHİR', 'NEVŞEHİR HACI BEKTAŞ VELİ ÜNİVERSİTESİ', 'Devlet', 'Nevşehir', 'http://www.nevsehir.edu.tr/', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1161, 'https://yokatlas.yok.gov.tr/assets/img/logo/306556.png', 'Niğde Ömer Halisdemir Üniversitesi Rektörlüğü Rektörlük Binası 2. Kat Merkez Yerleşke Bor Yolu Üzeri 51240 Merkez/NİĞDE', 'NİĞDE ÖMER HALİSDEMİR ÜNİVERSİTESİ', 'Devlet', 'Niğde', 'http://www.ohu.edu.tr/', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1162, 'https://yokatlas.yok.gov.tr/assets/img/logo/163891.png', 'Erkilet Dere Mah. Kuzey Çevreyolu Nuh Naci Yazgan Üniversitesi Kocasinan/Kayseri', 'NUH NACİ YAZGAN ÜNİVERSİTESİ', 'Vakıf', 'Kayseri', 'http://www.nny.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1163, 'https://yokatlas.yok.gov.tr/assets/img/logo/121946.png', 'Ondokuz Mayıs Üniversitesi Rektörlük Binası 
Kurupelit Kampüsü, 55139 Atakum / SAMSUN', 'ONDOKUZ MAYIS ÜNİVERSİTESİ', 'Devlet', 'Samsun', 'http://www.omu.edu.tr/', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1164, 'https://yokatlas.yok.gov.tr/assets/img/logo/122395.png', 'Cumhuriyet Yerleşkesi 52200 Altınordu/ORDU', 'ORDU ÜNİVERSİTESİ', 'Devlet', 'Ordu', 'http://www.odu.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1165, 'https://yokatlas.yok.gov.tr/assets/img/logo/122571.png', 'Orta Doğu Teknik Üniversitesi Üniversiteler Mah.Dumlupınar Blv.No:1 06800 Çankaya Ankara/TÜRKİYE', 'ORTA DOĞU TEKNİK ÜNİVERSİTESİ', 'Devlet', 'Ankara', 'http://www.metu.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1166, 'https://yokatlas.yok.gov.tr/assets/img/logo/122735.png', 'Karacaoğlan Yerleşkesi 80000
Merkez/OSMANİYE', 'OSMANİYE KORKUT ATA ÜNİVERSİTESİ', 'Devlet', 'Osmaniye', 'http://www.osmaniye.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1167, 'https://yokatlas.yok.gov.tr/assets/img/logo/324992.png', 'OSTİM Teknik Üniversitesi OSTİM, 06374 Ankara', 'OSTİM TEKNİK ÜNİVERSİTESİ', 'Vakıf', 'Ankara', 'www.ostimteknik.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1168, 'https://yokatlas.yok.gov.tr/assets/img/logo/122827.png', 'Nişantepe Mah. Orman Sok. No:34-36 Çekmeköy-İstanbul', 'ÖZYEĞİN ÜNİVERSİTESİ', 'Vakıf', 'İstanbul', 'www.ozyegin.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1169, 'https://yokatlas.yok.gov.tr/assets/img/logo/122831.png', 'Pamukkale Üniversitesi Rektörlüğü Kınıklı Yerleşkesi 20070 DENİZLİ', 'PAMUKKALE ÜNİVERSİTESİ', 'Devlet', 'Denizli', 'http://www.pau.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1170, 'https://yokatlas.yok.gov.tr/assets/img/logo/136233.png', 'Postane Mahallesi, Eflatun Sk. No:8, 34940 Tuzla/İSTANBUL', 'PİRİ REİS ÜNİVERSİTESİ', 'Vakıf', 'İstanbul', 'http://www.pirireis.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1171, 'https://yokatlas.yok.gov.tr/assets/img/logo/123221.png', 'Recep Tayyip Erdoğan Üniversitesi Zihni Derin Yerleşkesi, Fener Mah. 53100 RİZE', 'RECEP TAYYİP ERDOĞAN ÜNİVERSİTESİ', 'Devlet', 'Rize', 'erdogan.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1172, 'https://yokatlas.yok.gov.tr/assets/img/logo/123400.png', 'Sabancı Üniversite Orta Mah. Üniversite Caddesi No:27 34956 Orhanlı Tuzla İstanbu', 'SABANCI ÜNİVERSİTESİ', 'Vakıf', 'İstanbul', 'http://www.sabanciuniv.edu', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1173, 'https://yokatlas.yok.gov.tr/assets/img/logo/270121.png', 'Mekteb-i Tıbbiye-i Şahane (Haydarpaşa) Külliyesi, Selimiye Mah. Tıbbiye Cad. No:38 34668 ÜSKÜDAR/İSTANBUL', 'SAĞLIK BİLİMLERİ ÜNİVERSİTESİ', 'Devlet', 'İstanbul', 'http://www.sbu.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1174, 'https://yokatlas.yok.gov.tr/assets/img/logo/339988.png', 'Sakarya uygulamalı bilimler üniversitesi Esentepe Kampüsü Serdivan /Sakarya', 'SAKARYA UYGULAMALI BİLİMLER ÜNİVERSİTESİ', 'Devlet', 'Sakarya', 'www.subu.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1175, 'https://yokatlas.yok.gov.tr/assets/img/logo/123409.png', 'Sakarya Üniversitesi Esentepe Kampüsü 54187 Serdivan / SAKARYA', 'SAKARYA ÜNİVERSİTESİ', 'Devlet', 'Sakarya', 'http://www.sakarya.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1176, 'https://yokatlas.yok.gov.tr/assets/img/logo/339989.png', 'Gürgenyatak Mahallesi Canik/SAMSUN', 'SAMSUN ÜNİVERSİTESİ', 'Devlet', 'Samsun', 'www.samsun.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1177, 'https://yokatlas.yok.gov.tr/assets/img/logo/241177.png', 'İncilipınar Mah. Gazi Muhtar Paşa Bulv.                                               
No:36 27090 Şehitkamil/ GAZİANTEP', 'SANKO ÜNİVERSİTESİ', 'Vakıf', 'Gaziantep', 'http://www.sanko.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1178, 'https://yokatlas.yok.gov.tr/assets/img/logo/123902.png', 'Alaaddin Keykubat Kampüsü, Akademi Mahallesi, Yeni İstanbul Caddesi No:369/1 42130
Selçuklu-KONYA', 'SELÇUK ÜNİVERSİTESİ', 'Devlet', 'Konya', 'http://www.selcuk.edu.tr/', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1179, 'https://yokatlas.yok.gov.tr/assets/img/logo/124703.png', 'Kezer Yerleşkesi Veysel Karani Mah. Üniversite Cad. No:1 56100 Merkez/SİİRT', 'SİİRT ÜNİVERSİTESİ', 'Devlet', 'Siirt', 'http://siirt.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1180, 'https://yokatlas.yok.gov.tr/assets/img/logo/124805.png', 'Korucuk Köyü Trafo Mahallesi No:36  57000 ? SİNOP', 'SİNOP ÜNİVERSİTESİ', 'Devlet', 'Sinop', 'http://www.sinop.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1181, 'https://yokatlas.yok.gov.tr/assets/img/logo/339990.png', 'Gültepe Mahallesi Mecnun Otyakmaz Caddesi No:1 Merkez/Sivas', 'SİVAS BİLİM VE TEKNOLOJİ ÜNİVERSİTESİ', 'Devlet', 'Sivas', 'http://www.sivas.edu.tr/', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1182, 'https://yokatlas.yok.gov.tr/assets/img/logo/344737.png', 'Cumhuriyet Üniversitesi, Yenişehşr Mah. Kayseri Caddesi 58140 Kampüs SİVAS', 'SİVAS CUMHURİYET ÜNİVERSİTESİ', 'Devlet', 'Sivas', 'http://www.cumhuriyet.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1183, 'https://yokatlas.yok.gov.tr/assets/img/logo/124902.png', 'Süleyman Demirel Üniversitesi Batı Yerleşkesi Rektörlük Binası 32260  Çünür / ISPARTA', 'SÜLEYMAN DEMİREL ÜNİVERSİTESİ', 'Devlet', 'Isparta', 'http://www.sdu.edu.tr/', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1184, 'https://yokatlas.yok.gov.tr/assets/img/logo/125536.png', 'Yeni Mahalle Cizre Caddesi Mehmet Emin Acar Kampüsü
73000 Şırnak - Türkiye', 'ŞIRNAK ÜNİVERSİTESİ', 'Devlet', 'Şırnak', 'http://www.sirnak.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1185, 'https://yokatlas.yok.gov.tr/assets/img/logo/339991.png', 'Takbaş  Mah. Kartaltepe sokak 33400 Tarsus / MERSİN', 'TARSUS ÜNİVERSİTESİ', 'Devlet', 'Mersin', 'www.tarsus.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1186, 'https://yokatlas.yok.gov.tr/assets/img/logo/163892.png', 'TED Üniversitesi, Ziya Gökalp Caddesi No.48 06420, Kolej Çankaya ANKARA', 'TED ÜNİVERSİTESİ', 'Vakıf', 'Ankara', 'http://www.tedu.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1187, 'https://yokatlas.yok.gov.tr/assets/img/logo/356278.png', 'Namık Kemal Mah. Kampüs Cad. No:1 Merkez-TEKİRDAĞ', 'TEKİRDAĞ NAMIK KEMAL ÜNİVERSİTESİ', 'Devlet', 'Tekirdağ', 'http://www.nku.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1188, 'https://yokatlas.yok.gov.tr/assets/img/logo/125552.png', 'SÖĞÜTÖZÜ CADDESİ NO:43 ÇANKAYA/ANKARA', 'TOBB EKONOMİ VE TEKNOLOJİ ÜNİVERSİTESİ', 'Vakıf', 'Ankara', 'www.etu.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1189, 'https://yokatlas.yok.gov.tr/assets/img/logo/367245.png', 'Gaziosmanpaşa Üniversitesi Rektörlüğü Taşlıçiftlik Yerleşkesi TOKAT', 'TOKAT GAZİOSMANPAŞA ÜNİVERSİTESİ', 'Devlet', 'Tokat', 'www.gop.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1190, 'https://yokatlas.yok.gov.tr/assets/img/logo/163889.png', 'Bahçelievler Kampüsü 1857 Sokak No:12 33140 Yenişehir MERSİN', 'TOROS ÜNİVERSİTESİ', 'Vakıf', 'Mersin', 'www.toros.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1191, 'https://yokatlas.yok.gov.tr/assets/img/logo/339992.png', 'TRABZON ÜNİVERSİTESİ REKTÖRLÜĞÜ
Söğütlü Mahallesi
Adnan Kahveci Bulvarı
61335 – Akçaabat-Trabzon / TÜRKİYE', 'TRABZON ÜNİVERSİTESİ', 'Devlet', 'Trabzon', 'www.trabzon.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1192, 'https://yokatlas.yok.gov.tr/assets/img/logo/125577.png', 'Trakya Üniversitesi Rektörlüğü 22030 Balkan Yerleşkesi / EDİRNE', 'TRAKYA ÜNİVERSİTESİ', 'Devlet', 'Edirne', 'http://www.trakya.edu.tr/', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1193, 'https://yokatlas.yok.gov.tr/assets/img/logo/203267.png', 'Bahçekapı Mahallesi Okul Sokak No:11 Etimesgut / ANKARA', 'TÜRK HAVA KURUMU ÜNİVERSİTESİ', 'Vakıf', 'Ankara', 'http://www.thk.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1194, 'https://yokatlas.yok.gov.tr/assets/img/logo/201784.png', 'Şahinkaya Cad. No: 86 Beykoz/İSTANBUL', 'TÜRK-ALMAN ÜNİVERSİTESİ', 'Devlet', 'İstanbul', 'http://www.tau.edu.tr/', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1195, 'https://yokatlas.yok.gov.tr/assets/img/logo/125968.png', 'Ufuk Üniversitesi Rektörlüğü  Kızılcaşar Mahallesi İncek Bulvarı 06836 İncek/Gölbaşı/ANKARA', 'UFUK ÜNİVERSİTESİ', 'Vakıf', 'Ankara', 'http://www.ufuk.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1196, 'https://yokatlas.yok.gov.tr/assets/img/logo/126537.png', 'Uşak Üniversitesi Rektörlüğü 1 Eylül Kampüsü  64200 - UŞAK', 'UŞAK ÜNİVERSİTESİ', 'Devlet', 'Uşak', 'http://www.usak.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1197, 'https://yokatlas.yok.gov.tr/assets/img/logo/206795.png', 'Altunizade Mah.Haluk Türksoy Sok. No:14 Üsküdar/İstanbul', 'ÜSKÜDAR ÜNİVERSİTESİ', 'Vakıf', 'İstanbul', 'http://www.uskudar.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1198, 'https://yokatlas.yok.gov.tr/assets/img/logo/337414.png', 'Van Yüzüncü Yıl Üniversitesi Rektörlüğü, 65080, Kampüs / VAN', 'VAN YÜZÜNCÜ YIL ÜNİVERSİTESİ', 'Devlet', 'Van', 'http://www.yyu.edu.tr/', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1199, 'https://yokatlas.yok.gov.tr/assets/img/logo/126742.png', 'Çınarcık Yolu 2.km Merkez Kampüsü Yalova', 'YALOVA ÜNİVERSİTESİ', 'Devlet', 'Yalova', 'http://www.yalova.edu.tr/rektorluk', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1200, 'https://yokatlas.yok.gov.tr/assets/img/logo/126773.png', 'Üniversite Cad., No.:35-37, Ağaçlı Yol, Bornova-İZMİR', 'YAŞAR ÜNİVERSİTESİ', 'Vakıf', 'İzmir', 'http://www.yasar.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1201, 'https://yokatlas.yok.gov.tr/assets/img/logo/126818.png', '26 Ağustos Yerleşimi.Kayışdağı Cad.34755 Ataşehir/İstanbul', 'YEDİTEPE ÜNİVERSİTESİ', 'Vakıf', 'İstanbul', 'http://www.yeditepe.edu.tr/', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1202, 'https://yokatlas.yok.gov.tr/assets/img/logo/126982.png', 'Davutpaşa Mah. Davutpaşa Cad. 34220 Esenler - İstanbul', 'YILDIZ TEKNİK ÜNİVERSİTESİ', 'Devlet', 'İstanbul', 'http://www.yildiz.edu.tr', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1203, 'https://yokatlas.yok.gov.tr/assets/img/logo/359730.png', 'Medrese Mahallesi Adnan Menderes Bulvarı No:118 66200 Yozgat', 'YOZGAT BOZOK ÜNİVERSİTESİ', 'Devlet', 'Yozgat', 'http://www.bozok.edu.tr/', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1204, 'https://yokatlas.yok.gov.tr/assets/img/logo/206792.png', 'İşçi blokları mahallesi 1505. sokak Çankaya/ANKARA', 'YÜKSEK İHTİSAS ÜNİVERSİTESİ', 'Vakıf', 'Ankara', 'Yüksek İhtisas Üniversitesi', 'aktif');
INSERT INTO universities (id, logo, address, name, type, location, website, status) VALUES (1205, 'https://yokatlas.yok.gov.tr/assets/img/logo/365890.png', 'Zonguldak Bülent Ecevit Üniversitesi Rektörlüğü
İncivez-ZONGULDAK', 'ZONGULDAK BÜLENT ECEVİT ÜNİVERSİTESİ', 'Devlet', 'Zonguldak', 'https://www.beun.edu.tr', 'aktif');